INSERT INTO `clients` (`id`, `name`) VALUES
	(1, 'DANILO CATAPAN'),
	(2, 'DAIANE CATAPAN'),
	(3, 'ANGELINA CATAPAN'),
	(4, 'LUIGI CATAPAN'),
	(5, 'BENEDITO RODRIGUES'),
	(6, 'ALICE RODRIGUES'),
	(7, 'MARIA IZABEL RODRIGUES'),
	(8, 'MARCIA RODRIGUES'),
	(9, 'LUIZ ANTONIO RODRIGUES');